[program:cip-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/cip-platform/artisan queue:work redis --sleep=1 --tries=3 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/cip-queue.log
stopwaitsecs=30
