<?php

namespace App\Modules\Announcement\Domain;

interface AnnouncementRepositoryInterface
{
    /**
     * The payload must include organization_id, project_id, and source_id UUIDs.
     *
     * @param  array<string, mixed>  $data
     */
    public function insert(array $data): bool;

    /**
     * @return array<string, mixed>|null
     */
    public function findBySourceAndIdentityHash(
        string $organizationId,
        string $projectId,
        string $sourceId,
        string $identityHash,
    ): ?array;

    /**
     * Return the UUID generated by the most recent successful insert.
     */
    public function lastInsertId(): string;

    public function markUnchanged(
        string $organizationId,
        string $projectId,
        string $sourceId,
        string $itemId,
        string $lastSeenAtUtc,
        string $updatedAtUtc,
    ): bool;

    /**
     * @param  array<string, mixed>  $data
     */
    public function applyContentUpdate(
        string $organizationId,
        string $projectId,
        string $sourceId,
        string $itemId,
        array $data,
    ): int|false;

    /**
     * @param  array<string, mixed>  $criteria
     * @return array<string, mixed>
     */
    public function findPage(
        string $organizationId,
        string $projectId,
        array $criteria,
    ): array;

    /**
     * @return array<string, mixed>
     */
    public function findById(
        string $organizationId,
        string $projectId,
        string $itemId,
    ): array;

    /**
     * @return array<string, mixed>
     */
    public function findEditorialSummary(
        string $organizationId,
        string $projectId,
    ): array;
}
